language: java

install: true

script: mvn clean verify

after_success:
  # Upload the repository to the snapshot update site on Bintray
  # 1. Delete the snapshot version
  - curl -X DELETE -ukaloyan-raev:$BINTRAY_KEY https://api.bintray.com/packages/kaloyan-raev/default-text-editor/update-site/versions/snapshot
  # 2. Upload the repository.zip to a new version with name "snapshot", unzip it and publish it
  - curl -T org.eclipselabs.dte-repository/target/repository.zip -ukaloyan-raev:$BINTRAY_KEY "https://api.bintray.com/content/kaloyan-raev/default-text-editor/update-site/snapshot/snapshot/repository.zip?publish=1&explode=1"
